export const MAX_FILE_SIZE_BYTES = 1024 * 1024; // 1 MB
export const WARNING_TOKEN_THRESHOLD = 12_000;
export const DEFAULT_COMMIT_TOKENS = 1_500;
export const DEFAULT_REVIEW_TOKENS = 5_000;
export const DEFAULT_LLM_MODEL = 'gpt-4o';
export const DEFAULT_PRICE_PER_MILLION = 5;

const BINARY_EXTENSION_LIST = [
  '.png',
  '.jpg',
  '.jpeg',
  '.webp',
  '.gif',
  '.bmp',
  '.ico',
  '.tif',
  '.tiff',
  '.psd',
  '.ai',
  '.sketch',
  '.heic',
  '.heif',
  '.mp3',
  '.wav',
  '.flac',
  '.ogg',
  '.m4a',
  '.mp4',
  '.mkv',
  '.mov',
  '.avi',
  '.webm',
  '.wmv',
  '.flv',
  '.mpg',
  '.mpeg',
  '.ogv',
  '.zip',
  '.gz',
  '.tgz',
  '.bz2',
  '.xz',
  '.rar',
  '.7z',
  '.tar',
  '.pdf',
  '.exe',
  '.dll',
  '.so',
  '.dylib',
  '.class',
  '.jar',
  '.war',
  '.ear',
  '.ttf',
  '.otf',
  '.woff',
  '.woff2',
  '.eot',
  '.bin',
  '.pak',
  '.dat',
];

const KNOWN_TEXT_LIST = [
  // Web / JS
  '.js',
  '.jsx',
  '.ts',
  '.tsx',
  '.mjs',
  '.cjs',
  '.json',
  '.html',
  '.css',
  '.scss',
  '.less',
  '.vue',
  '.svelte',
  // Backend / System
  '.java',
  '.py',
  '.c',
  '.cpp',
  '.h',
  '.hpp',
  '.cs',
  '.go',
  '.rs',
  '.php',
  '.rb',
  '.swift',
  '.kt',
  '.dart',
  '.scala',
  '.pl',
  '.lua',
  '.sh',
  '.bat',
  // Data / Docs
  '.md',
  '.txt',
  '.xml',
  '.yaml',
  '.yml',
  '.sql',
  '.graphql',
  '.toml',
  '.ini',
  '.env',
  // Config
  '.gitignore',
  '.dockerignore',
  'dockerfile',
  '.editorconfig',
];

const createLowercaseSet = (values: string[]): ReadonlySet<string> =>
  new Set(values.map((value) => value.toLowerCase()));

export const BINARY_EXTENSIONS = createLowercaseSet(BINARY_EXTENSION_LIST);
export const KNOWN_TEXT_EXTENSIONS = createLowercaseSet(KNOWN_TEXT_LIST);
