import type { Config } from '../types';

export const DEFAULT_CONFIG: Config = {
  MAX_FILE_SIZE_BYTES: 1 * 1024 * 1024,
  EXCLUDED_DIRS: new Set([
    ".git",
    ".github",
    ".idea",
    ".vscode",
    "node_modules",
    "dist",
    "build",
    "coverage",
    "public",
    "vendor",
    ".cache",
    ".next",
    ".nuxt",
    ".svelte-kit",
    "__pycache__",
    ".venv",
    "env",
    "target",
    "out",
    "bin",
    "obj",
    "log",
    "logs",
  ]),
  EXCLUDED_FILES: new Set([
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    ".env",
    ".DS_Store",
  ]),
  EXCLUDED_PATTERNS: new Set([
    "*.svg",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.webp",
    "*.ico",
    "*.mp4",
    "*.mov",
    "*.avi",
    "*.webm",
    "*.pdf",
    "*.zip",
    "*.rar",
    "*.gz",
    "*.lockb",
  ]),
  INCLUDED_EXTENSIONS_AND_FILENAMES: new Set([
    "package.json",
    "pom.xml",
    "pyproject.toml",
    "requirements.txt",
    "go.mod",
    "Cargo.toml",
    "composer.json",
    "Dockerfile",
    "docker-compose.yml",
    "Makefile",
    "README.md",
    ".js",
    ".mjs",
    ".cjs",
    ".ts",
    ".mts",
    ".cts",
    ".jsx",
    ".tsx",
    ".json",
    ".html",
    ".htm",
    ".css",
    ".scss",
    ".sass",
  ]),
};
